#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

# the "app_ulrich_about" route name is not important yet
# app_ulrich_about:
   # path: /ulrich/about
   #controller: App\Controller\UlrichController::route